### PR TITLE
 Fix for New-Password endless loop on .Net Core

### PR DESCRIPTION
**Pull request by y0rik**
Hello Pavel,
I've been enjoying your module a lot until I discovered a problem when it runs on powershell core.
After some research I implemented the fix, that resolves this issue.
I also removed ` powershell escaping symbol from the generating string, since it causes issues

Please let me know what you think.
I'm sorry for the mess in commits. I was going to implement a workaround in the first place.

### CODE REVIEW

**Comment by pgarm** [comment]
Thanks Yuriy, glad to see this is useful to someone else and not just me.
Sorry for slow response, been up to me eyeballs with main job recently.

Never imagined it would be used outside of Windows environments, so good catch there with cross-platform testing.
I'll run some tests myself on weekend and merge/publish then.

**Comment by y0rik** [comment]
Hey Pavel,
No worries at all, thanks for getting back to this. Yeah, powershell is hitting more and more non-windows computers nowadays, kudos to MS for that!
Take your time and let me know if you need anything.

**Comment by pgarm** [comment]
Sorry m8, took too long to actually get this tested for some of the backend deployments with clients.
I've merged the PR, will add a few touches today and republish in Gallery.

**Comment by pgarm** [comment]
Published in gallery as 0.2.789.560

**Pull request merged**
